<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $products = [
            [
                'name' => 'Titus 20kg',
                'quantity' => 'Full Carton',
                'demand_increase' => 9,
                'total_slot' => 5,
                'slot_booked' => 3,
                'expiry_date' => '2022-12-20 00:00:00',
                'delivery_date' => '2022-12-20 00:00:00',
                'image_thumbnail' => 'Product-img1.png',
                'slot_per_person' => '4kg',
                'is_in_season' => true,
                'is_recommend' => false,
                'price' => 7500,
                'old_price' => 8500,
                'status' => 'Pending',
                'quantity_remaining' => 5,
                'initial_quantity' => 50,
                'unit' => "Kg",
                'category' => 'Shop',
            ],
            [
                'name' => 'Croaker Fish',
                'quantity' => 'Full Carton',
                'demand_increase' => 8,
                'total_slot' => 5,
                'slot_booked' => 3,
                'expiry_date' => '2022-12-20 00:00:00',
                'delivery_date' => '2022-12-20 00:00:00',
                'image_thumbnail' => 'Product-img2.png',
                'slot_per_person' => '5kg',
                'is_in_season' => false,
                'is_recommend' => false,
                'price' => 10000,
                'old_price' => 12000,
                'status' => 'Pending',
                'quantity_remaining' => 5,
                'initial_quantity' => 50,
                'unit' => "Kg",
                'category' => 'Shop',
            ],
            [
                'name' => 'White Onions',
                'quantity' => '40kg',
                'demand_increase' => 10,
                'total_slot' => 10,
                'slot_booked' => 2,
                'expiry_date' => '2022-12-25 00:00:00',
                'delivery_date' => '2022-12-22 00:00:00',
                'image_thumbnail' => 'Product-img3.png',
                'slot_per_person' => '4kg',
                'is_in_season' => true,
                'is_recommend' => false,
                'price' => 5000,
                'old_price' => 7000,
                'status' => 'Pending',
                'quantity_remaining' => 6,
                'initial_quantity' => 100,
                'unit' => "Kg",
                'category' => 'Shop',
            ],
            [
                'name' => 'Guinea Corn Red',
                'quantity' => 'Paint Bucket',
                'demand_increase' => 15,
                'total_slot' => 15,
                'slot_booked' => 3,
                'expiry_date' => '2022-12-20 00:00:00',
                'delivery_date' => '2022-12-20 00:00:00',
                'image_thumbnail' => 'Product-img2.png',
                'slot_per_person' => '5kg',
                'is_in_season' => false,
                'is_recommend' => false,
                'price' => 20000,
                'old_price' => 23000,
                'status' => 'Pending',
                'quantity_remaining' => 10,
                'initial_quantity' => 25,
                'unit' => "Kg",
                'category' => 'Shop',
            ],
            [
                'name' => 'Soya Beans',
                'quantity' => 'Paint Bucket',
                'demand_increase' => 45,
                'total_slot' => 2,
                'slot_booked' => 1,
                'expiry_date' => '2022-12-28 00:00:00',
                'delivery_date' => '2022-12-28 00:00:00',
                'image_thumbnail' => 'Product-img5.png',
                'slot_per_person' => '5kg',
                'is_in_season' => true,
                'is_recommend' => false,
                'price' => 11000,
                'old_price' => 14000,
                'status' => 'Pending',
                'quantity_remaining' => 30,
                'initial_quantity' => 150,
                'unit' => "Kg",
                'category' => 'Shop',
            ],
            [
                'name' => 'Soya Beans',
                'quantity' => '100kg',
                'demand_increase' => 17,
                'total_slot' => 25,
                'slot_booked' => 12,
                'expiry_date' => '2022-12-20 00:00:00',
                'delivery_date' => '2022-12-20 00:00:00',
                'image_thumbnail' => 'Product-img6.png',
                'slot_per_person' => '5kg',
                'is_in_season' => false,
                'is_recommend' => false,
                'price' => 17000,
                'old_price' => 22000,
                'status' => 'Pending',
                'quantity_remaining' => 5,
                'initial_quantity' => 50,
                'unit' => "Kg",
                'category' => 'Shop',
            ],
            [
                'name' => 'Tuwo Rice',
                'quantity' => '50kg',
                'demand_increase' => 8,
                'total_slot' => 5,
                'slot_booked' => 3,
                'expiry_date' => '2022-12-20 00:00:00',
                'delivery_date' => '2022-12-20 00:00:00',
                'image_thumbnail' => 'Product-img7.png',
                'slot_per_person' => '5kg',
                'is_in_season' => true,
                'is_recommend' => false,
                'price' => 25000,
                'old_price' => 27000,
                'status' => 'Pending',
                'quantity_remaining' => 5,
                'initial_quantity' => 50,
                'unit' => "Kg",
                'category' => 'Shop',
            ],
            [
                'name' => 'Beans Oloyin - original',
                'quantity' => '100kg',
                'demand_increase' => 8,
                'total_slot' => 10,
                'slot_booked' => 7,
                'expiry_date' => '2022-12-20 00:00:00',
                'delivery_date' => '2022-12-20 00:00:00',
                'image_thumbnail' => 'Product-img8.png',
                'slot_per_person' => '5kg',
                'is_in_season' => false,
                'is_recommend' => false,
                'price' => 35000,
                'old_price' => 45000,
                'status' => 'Pending',
                'quantity_remaining' => 5,
                'initial_quantity' => 50,
                'unit' => "Kg",
                'category' => 'Shop',
            ],
            [
                'name' => 'Irish Potato',
                'quantity' => '5kg',
                'demand_increase' => 8,
                'total_slot' => 15,
                'slot_booked' => 7,
                'expiry_date' => '2022-12-20 00:00:00',
                'delivery_date' => '2022-12-20 00:00:00',
                'image_thumbnail' => 'Product-img9.png',
                'slot_per_person' => '5kg',
                'is_in_season' => true,
                'is_recommend' => false,
                'price' => 26000,
                'old_price' => 30000,
                'status' => 'Pending',
                'quantity_remaining' => 5,
                'initial_quantity' => 50,
                'unit' => "Kg",
                'category' => 'Shop',
            ],
            [
                'name' => 'Ofada Rice',
                'quantity' => '10kg',
                'demand_increase' => 8,
                'total_slot' => 10,
                'slot_booked' => 7,
                'expiry_date' => '2022-12-20 00:00:00',
                'delivery_date' => '2022-12-20 00:00:00',
                'image_thumbnail' => 'Product-img10.png',
                'slot_per_person' => '5kg',
                'is_in_season' => false,
                'is_recommend' => false,
                'price' => 35000,
                'old_price' => 45000,
                'status' => 'Pending',
                'quantity_remaining' => 5,
                'initial_quantity' => 50,
                'unit' => "Kg",
                'category' => 'Shop',
            ],
            [
                'name' => 'Sombo Pepper - Grade',
                'quantity' => 'Paint Bucket',
                'demand_increase' => 8,
                'total_slot' => 10,
                'slot_booked' => 7,
                'expiry_date' => '2022-12-20 00:00:00',
                'delivery_date' => '2022-12-20 00:00:00',
                'image_thumbnail' => 'Product-img11.png',
                'slot_per_person' => '5kg',
                'is_in_season' => true,
                'is_recommend' => false,
                'price' => 35000,
                'old_price' => 45000,
                'status' => 'Pending',
                'quantity_remaining' => 5,
                'initial_quantity' => 50,
                'unit' => "Kg",
                'category' => 'Shop',
            ],
            [
                'name' => 'Plantain Big Unripe',
                'quantity' => 'Stem',
                'demand_increase' => 8,
                'total_slot' => 10,
                'slot_booked' => 7,
                'expiry_date' => '2022-12-20 00:00:00',
                'delivery_date' => '2022-12-20 00:00:00',
                'image_thumbnail' => 'Product-img12.png',
                'slot_per_person' => '5kg',
                'is_in_season' => true,
                'is_recommend' => false,
                'price' => 35000,
                'old_price' => 45000,
                'status' => 'Pending',
                'quantity_remaining' => 5,
                'initial_quantity' => 50,
                'unit' => "Kg",
                'category' => 'Shop',
            ],
            [
                'name' => 'Titus 20kg',
                'quantity' => 'Full Carton',
                'demand_increase' => 9,
                'total_slot' => 5,
                'slot_booked' => 3,
                'expiry_date' => '2022-12-20 00:00:00',
                'delivery_date' => '2022-12-20 00:00:00',
                'image_thumbnail' => 'Product-img1.png',
                'slot_per_person' => '4kg',
                'is_in_season' => true,
                'is_recommend' => false,
                'price' => 7500,
                'old_price' => 8500,
                'status' => 'Pending',
                'quantity_remaining' => 5,
                'initial_quantity' => 50,
                'unit' => "Kg",
                'category' => 'Pally',
            ],
            [
                'name' => 'Croaker Fish',
                'quantity' => 'Full Carton',
                'demand_increase' => 8,
                'total_slot' => 5,
                'slot_booked' => 3,
                'expiry_date' => '2022-12-20 00:00:00',
                'delivery_date' => '2022-12-20 00:00:00',
                'image_thumbnail' => 'Product-img2.png',
                'slot_per_person' => '5kg',
                'is_in_season' => false,
                'is_recommend' => false,
                'price' => 10000,
                'old_price' => 12000,
                'status' => 'Pending',
                'quantity_remaining' => 5,
                'initial_quantity' => 50,
                'unit' => "Kg",
                'category' => 'Pally',
            ],
            [
                'name' => 'White Onions',
                'quantity' => '40kg',
                'demand_increase' => 10,
                'total_slot' => 10,
                'slot_booked' => 2,
                'expiry_date' => '2022-12-25 00:00:00',
                'delivery_date' => '2022-12-22 00:00:00',
                'image_thumbnail' => 'Product-img3.png',
                'slot_per_person' => '4kg',
                'is_in_season' => true,
                'is_recommend' => false,
                'price' => 5000,
                'old_price' => 7000,
                'status' => 'Pending',
                'quantity_remaining' => 6,
                'initial_quantity' => 100,
                'unit' => "Kg",
                'category' => 'Pally',
            ],
            [
                'name' => 'Guinea Corn Red',
                'quantity' => 'Paint Bucket',
                'demand_increase' => 15,
                'total_slot' => 15,
                'slot_booked' => 3,
                'expiry_date' => '2022-12-20 00:00:00',
                'delivery_date' => '2022-12-20 00:00:00',
                'image_thumbnail' => 'Product-img2.png',
                'slot_per_person' => '5kg',
                'is_in_season' => false,
                'is_recommend' => false,
                'price' => 20000,
                'old_price' => 23000,
                'status' => 'Pending',
                'quantity_remaining' => 10,
                'initial_quantity' => 25,
                'unit' => "Kg",
                'category' => 'Pally',
            ],
            [
                'name' => 'Soya Beans',
                'quantity' => 'Paint Bucket',
                'demand_increase' => 45,
                'total_slot' => 2,
                'slot_booked' => 1,
                'expiry_date' => '2022-12-28 00:00:00',
                'delivery_date' => '2022-12-28 00:00:00',
                'image_thumbnail' => 'Product-img5.png',
                'slot_per_person' => '5kg',
                'is_in_season' => true,
                'is_recommend' => false,
                'price' => 11000,
                'old_price' => 14000,
                'status' => 'Pending',
                'quantity_remaining' => 30,
                'initial_quantity' => 150,
                'unit' => "Kg",
                'category' => 'Pally',
            ],
            [
                'name' => 'Soya Beans',
                'quantity' => '100kg',
                'demand_increase' => 17,
                'total_slot' => 25,
                'slot_booked' => 12,
                'expiry_date' => '2022-12-20 00:00:00',
                'delivery_date' => '2022-12-20 00:00:00',
                'image_thumbnail' => 'Product-img6.png',
                'slot_per_person' => '5kg',
                'is_in_season' => false,
                'is_recommend' => false,
                'price' => 17000,
                'old_price' => 22000,
                'status' => 'Pending',
                'quantity_remaining' => 5,
                'initial_quantity' => 50,
                'unit' => "Kg",
                'category' => 'Pally',
            ],
            [
                'name' => 'Tuwo Rice',
                'quantity' => '50kg',
                'demand_increase' => 8,
                'total_slot' => 5,
                'slot_booked' => 3,
                'expiry_date' => '2022-12-20 00:00:00',
                'delivery_date' => '2022-12-20 00:00:00',
                'image_thumbnail' => 'Product-img7.png',
                'slot_per_person' => '5kg',
                'is_in_season' => true,
                'is_recommend' => false,
                'price' => 25000,
                'old_price' => 27000,
                'status' => 'Pending',
                'quantity_remaining' => 5,
                'initial_quantity' => 50,
                'unit' => "Kg",
                'category' => 'Pally',
            ],
            [
                'name' => 'Beans Oloyin - original',
                'quantity' => '100kg',
                'demand_increase' => 8,
                'total_slot' => 10,
                'slot_booked' => 7,
                'expiry_date' => '2022-12-20 00:00:00',
                'delivery_date' => '2022-12-20 00:00:00',
                'image_thumbnail' => 'Product-img8.png',
                'slot_per_person' => '5kg',
                'is_in_season' => false,
                'is_recommend' => false,
                'price' => 35000,
                'old_price' => 45000,
                'status' => 'Pending',
                'quantity_remaining' => 5,
                'initial_quantity' => 50,
                'unit' => "Kg",
                'category' => 'Pally',
            ],
            [
                'name' => 'Irish Potato',
                'quantity' => '5kg',
                'demand_increase' => 8,
                'total_slot' => 15,
                'slot_booked' => 7,
                'expiry_date' => '2022-12-20 00:00:00',
                'delivery_date' => '2022-12-20 00:00:00',
                'image_thumbnail' => 'Product-img9.png',
                'slot_per_person' => '5kg',
                'is_in_season' => true,
                'is_recommend' => false,
                'price' => 26000,
                'old_price' => 30000,
                'status' => 'Pending',
                'quantity_remaining' => 5,
                'initial_quantity' => 50,
                'unit' => "Kg",
                'category' => 'Pally',
            ],
            [
                'name' => 'Ofada Rice',
                'quantity' => '10kg',
                'demand_increase' => 8,
                'total_slot' => 10,
                'slot_booked' => 7,
                'expiry_date' => '2022-12-20 00:00:00',
                'delivery_date' => '2022-12-20 00:00:00',
                'image_thumbnail' => 'Product-img10.png',
                'slot_per_person' => '5kg',
                'is_in_season' => false,
                'is_recommend' => false,
                'price' => 35000,
                'old_price' => 45000,
                'status' => 'Pending',
                'quantity_remaining' => 5,
                'initial_quantity' => 50,
                'unit' => "Kg",
                'category' => 'Pally',
            ],
            [
                'name' => 'Sombo Pepper - Grade',
                'quantity' => 'Paint Bucket',
                'demand_increase' => 8,
                'total_slot' => 10,
                'slot_booked' => 7,
                'expiry_date' => '2022-12-20 00:00:00',
                'delivery_date' => '2022-12-20 00:00:00',
                'image_thumbnail' => 'Product-img11.png',
                'slot_per_person' => '5kg',
                'is_in_season' => true,
                'is_recommend' => false,
                'price' => 35000,
                'old_price' => 45000,
                'status' => 'Pending',
                'quantity_remaining' => 5,
                'initial_quantity' => 50,
                'unit' => "Kg",
                'category' => 'Pally',
            ],
            [
                'name' => 'Plantain Big Unripe',
                'quantity' => 'Stem',
                'demand_increase' => 8,
                'total_slot' => 10,
                'slot_booked' => 7,
                'expiry_date' => '2022-12-20 00:00:00',
                'delivery_date' => '2022-12-20 00:00:00',
                'image_thumbnail' => 'Product-img12.png',
                'slot_per_person' => '5kg',
                'is_in_season' => true,
                'is_recommend' => false,
                'price' => 35000,
                'old_price' => 45000,
                'status' => 'Pending',
                'quantity_remaining' => 5,
                'initial_quantity' => 50,
                'unit' => "Kg",
                'category' => 'Pally',
            ],
            [
                'name' => 'Strawberries',
                'quantity' => '10kg',
                'demand_increase' => 8,
                'total_slot' => 10,
                'slot_booked' => 7,
                'expiry_date' => '2022-12-20 00:00:00',
                'delivery_date' => '2022-12-20 00:00:00',
                'image_thumbnail' => 'Pre-order1.png',
                'slot_per_person' => '5kg',
                'is_in_season' => true,
                'is_recommend' => true,
                'price' => 35000,
                'old_price' => 45000,
                'status' => 'Pending',
                'quantity_remaining' => 7,
                'initial_quantity' => 10,
                'unit' => "Kg",
                'category' => 'Recommend',
            ],
            [
                'name' => 'Strawberries',
                'quantity' => '10kg',
                'demand_increase' => 8,
                'total_slot' => 10,
                'slot_booked' => 7,
                'expiry_date' => '2022-12-20 00:00:00',
                'delivery_date' => '2022-12-17 00:00:00',
                'image_thumbnail' => 'Pre-order2.png',
                'slot_per_person' => '5kg',
                'is_in_season' => false,
                'is_recommend' => true,
                'price' => 35000,
                'old_price' => 45000,
                'status' => 'Pending',
                'quantity_remaining' => 2,
                'initial_quantity' => 16,
                'unit' => "Kg",
                'category' => 'Recommend',
            ],
            [
                'name' => 'Strawberries',
                'quantity' => '10kg',
                'demand_increase' => 8,
                'total_slot' => 10,
                'slot_booked' => 7,
                'expiry_date' => '2022-12-20 00:00:00',
                'delivery_date' => '2022-12-14 00:00:00',
                'image_thumbnail' => 'Pre-order3.png',
                'slot_per_person' => '5kg',
                'is_in_season' => true,
                'is_recommend' => true,
                'price' => 35000,
                'old_price' => 45000,
                'status' => 'Pending',
                'quantity_remaining' => 0,
                'initial_quantity' => 16,
                'unit' => "Kg",
                'category' => 'Recommend',
            ],
        ];

        foreach($products as $product)
            Db::table('products')->insert($product);
    }
}
